// Fills the LOCAL Supabase with test accounts and a sample tournament.
// Refuses to run against anything that isn't on this machine.
//
//   npm run seed
//
// Test logins are written to supabase/local-users.json (git-ignored). The password is generated
// on first run; sign in at http://127.0.0.1:3000 with any of those emails.
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import ws from 'ws';

// Node 20 has no built-in WebSocket; supabase-js wants one even though these scripts don't use live updates.
export const client = (url, key) => createClient(url, key, { auth: { persistSession: false }, realtime: { transport: ws } });

export function localEnv() {
  const env = JSON.parse(execSync('npx supabase status -o json', { stdio: ['ignore', 'pipe', 'ignore'] }).toString());
  const url = env.API_URL, service = env.SERVICE_ROLE_KEY || env.SECRET_KEY, anon = env.ANON_KEY || env.PUBLISHABLE_KEY;
  if (!/^http:\/\/(127\.0\.0\.1|localhost):/.test(url)) throw new Error('Not a local Supabase: ' + url);
  return { url, service, anon };
}
const USERS_FILE = new URL('../supabase/local-users.json', import.meta.url);
export function localUsers() {
  if (!existsSync(USERS_FILE)) {
    const password = randomBytes(9).toString('base64url');
    const people = [['admin', 'Alex', 'Admin'], ['bob', 'Bob', 'Baker'], ['cara', 'Cara', 'Chen'], ['dan', 'Dan', 'Diaz'], ['eve', 'Eve', 'Evans'], ['finn', 'Finn', 'Ford']];
    writeFileSync(USERS_FILE, JSON.stringify({
      note: 'Local test accounts only. Generated by scripts/seed-local.mjs.',
      password, users: people.map(([id, first, last]) => ({ id: 'test-' + id, email: `${id}@poker.test`, first, last, admin: id === 'admin' })),
    }, null, 2));
  }
  return JSON.parse(readFileSync(USERS_FILE, 'utf8'));
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const env = localEnv(), { password, users } = localUsers();
  const db = client(env.url, env.service);
  const ok = r => { if (r.error) throw new Error(r.error.message); return r.data; };
  for (const u of users) {
    const r = await db.auth.admin.createUser({ email: u.email, password, email_confirm: true });
    if (r.error && !/already/i.test(r.error.message)) throw new Error(r.error.message);
    ok(await db.from('poker_profiles').upsert({ id: u.id, first: u.first, last: u.last, email: u.email }));
    if (u.admin) ok(await db.from('poker_admins').upsert({ email: u.email }));
  }
  // A sample tournament with one finished live session, so stacks carry into the online table.
  const ids = users.map(u => u.id);
  const tournament = {
    id: 'test-tournament', status: 'active', endedAt: null, final: null,
    settings: { name: 'Test Tournament', buyIn: 10, chipsPerBuyIn: 200, minPct: 75, p1: 70, p2: 20, admin: 10 },
    sessions: [{ date: new Date().toISOString().slice(0, 10) }],
    players: ids.slice(0, 5).map(id => ({ id })),
    buyIns: ids.slice(0, 5).map((id, i) => ({ id: 'b' + i, playerId: id, session: 1, count: 1 })),
    chips: { 1: Object.fromEntries(ids.slice(0, 5).map((id, i) => [id, [320, 260, 200, 140, 80][i]])) },
  };
  const row = ok(await db.from('poker_state').select('version').eq('id', 'main').single());
  ok(await db.from('poker_state').update({ data: { tournaments: [tournament] }, version: row.version + 1 }).eq('id', 'main'));
  console.log(`Seeded ${users.length} test accounts (${users.map(u => u.email).join(', ')}).`);
  console.log('Password is in supabase/local-users.json');
}
